DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'EVENT_TYPE') THEN
CREATE TYPE EVENT_TYPE AS ENUM ('BIRTHDAY', 'WEDDING', 'CARPORATE', 'GRADUATIONEVENT', 'CHRISTENING');
END IF;
END $$;