DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'EventType') THEN
CREATE TYPE EventType AS ENUM ('BIRTHDAY', 'WEDDING', 'CARPORATE', 'GRADUATIONEVENT', 'CHRISTENING');
END IF;
END $$;