DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'eventType') THEN
CREATE TYPE eventType AS ENUM ('BIRTHDAY', 'WEDDING', 'CARPORATE', 'GRADUATIONEVENT', 'CHRISTENING');
END IF;
END $$;