DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'event_type') THEN
CREATE TYPE event_type AS ENUM ('BIRTHDAY', 'WEDDING', 'CARPORATE', 'GRADUATION_EVENT', 'CHRISTENING');
END IF;
END $$;